@startuml
scale 2
class Publico {
    -dni: string
    -nombre: string
    -direccion: string
    -telefono: integer  
     + Dni()  
     + Nombre()  
     + Direccion()  
     + Telefono()  
}

class Abonado {
    -numeroSocio: integer 
    + NumeroSocio()
    + CompraEntrada()
}

class Simpatizante {
    -fechaAlta: DateTime 
    + FechaAlta()
    + CompraEntrada()
}

class Partido {
    -codigo: integer
    -nombre: string
    -fecha: DateTime
    + Codigo()
    + Nombre()
    + Fecha()
    + VentaEntrada()
}

class Entrada {
    -precio: float
    -numeroAsiento: integer
    + Precio()
    + NumeroAsiento()
}

Publico <|-- Abonado
Publico <|-- Simpatizante
Partido "1" *-- "*" Entrada
Abonado "1" --- "0..5" Entrada
Simpatizante "1" --- "0..1" Entrada
@enduml
